OfflineExamSystem/Controllers/UserAdminController.cs
using Microsoft.AspNet.Identity.Owin;
using OfflineExamSystem.DDL.Repository;
using OfflineExamSystem.Helpers;
using OfflineExamSystem.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OfflineExamSystem.Controllers
{
    [LocalizedAuthorize(Roles = "Admin")]
    public class UsersAdminController : BaseController
    {
        #region Private Fields
        private ApplicationDbContext db = new ApplicationDbContext();

        private ApplicationUserManager _userManager;
        // Add the Group Manager (NOTE: only access through the public
        // Property, not by the instance variable!)
        private ApplicationGroupManager _groupManager;
        private ApplicationRoleManager _roleManager;
        #endregion Private Fields

        #region Public Constructors
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        #endregion Public Constructors

        #region Public Properties
        public ApplicationUserManager UserManager
        {
            get => _userManager ?? HttpContext.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>();
            private set => _userManager = value;
        }
        public ApplicationGroupManager GroupManager
        {
            get => _groupManager ?? new ApplicationGroupManager();
            private set => _groupManager = value;
        }
        public ApplicationRoleManager RoleManager
        {
            get => _roleManager ?? HttpContext.GetOwinContext()
                    .Get<ApplicationRoleManager>();
            private set => _roleManager = value;
        }
        #endregion Public Properties

        #region Public Methods
        public ActionResult GetRoles(string searchTerm, int pageSize, int pageNum)
        {
            //Get the paged results and the total count of the results for this query.
            RoleRepository ur = new RoleRepository();
            List<ApplicationRole> roles = ur.GetRoles(searchTerm, pageSize, pageNum);
            int count = ur.GetRolesCount(searchTerm, pageSize, pageNum);
            //Translate the roles into a format the select2 dropdown expects
            Select2PagedResult pagedRoles = ur.ToSelect2Format(roles, count);

            //Return the data as a jsonp result
            return new JsonResultHelper
            {
                Data = pagedRoles,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public PartialViewResult UserGrid(string username, string roleId, string emailConfirmed, int? page, int? rows, string sort, string order)
        {
            IQueryable<IndexUserViewModel> query = (from u in UserManager.Users select new IndexUserViewModel { Id = u.Id, UserName = u.UserName, Email = u.Email, EmailConfirmed = u.EmailConfirmed, Roles = u.Roles }).AsQueryable();
            if (!string.IsNullOrEmpty(username))
            {
                query = query.Where(q => q.UserName.ToLower().Contains(username.ToLower()));
            }

            if (!string.IsNullOrEmpty(roleId))
            {
                query = query.Where(q => q.Roles.Any(r => r.RoleId == roleId));
            }

            if (!string.IsNullOrEmpty(emailConfirmed))
            {
                bool isEmailConfirmed = bool.Parse(emailConfirmed);
                query = query.Where(f => f.EmailConfirmed == isEmailConfirmed);
            }
            if (!string.IsNullOrWhiteSpace(sort))
            {
                switch (sort.ToLower())
                {
                    case "username":
                        if (order == "asc")
                        {
                            query = query.OrderBy(q => q.UserName);
                        }
                        else
                        {
                            query = query.OrderByDescending(q => q.UserName);
                        }

                        break;
                    case "email":
                        if (order == "asc")
                        {
                            query = query.OrderBy(q => q.Email);
                        }
                        else
                        {
                            query = query.OrderByDescending(q => q.Email);
                        }

                        break;

                    case "emailconfirmed":
                        if (order == "asc")
                        {
                            query = query.OrderBy(q => q.EmailConfirmed);
                        }
                        else
                        {
                            query = query.OrderByDescending(q => q.EmailConfirmed);
                        }

                        break;

                    case "id":
                        if (order == "asc")
                        {
                            query = query.OrderBy(q => q.Id);
                        }
                        else
                        {
                            query = query.OrderByDescending(q => q.Id);
                        }

                        break;

                    default:
                        query = query.OrderByDescending(q => q.Id);
                        break;
                }
            }
            else
            {
                query = query.OrderBy(q => q.Id);
            }
            ViewBag.TotalRows = query.Count();
            return PartialView("_UserGrid", query.Skip((page - 1 ?? 0) * (rows ?? 10)).Take(rows ?? 10).ToList());
        }

        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            // Show the groups the user belongs to:
            IEnumerable<ApplicationGroup> userGroups = await GroupManager.GetUserGroupsAsync(id);
            DetailsUserViewModel detailsUserViewModel = new DetailsUserViewModel(user, userGroups);
            return PartialView("Details", detailsUserViewModel);
        }
        public async Task<ActionResult> Roles(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUser user = await UserManager.FindByIdAsync(id);
            ViewBag.UserName = user.UserName;
            IQueryable<IndexUserRolesViewModel> userRoles = from r in db.Roles
                                                            join ur in db.ApplicationUserRole on r.Id equals ur.RoleId
                                                            join u in db.Users on user.Id equals u.Id
                                                            where ur.UserId == id
                                                            select new IndexUserRolesViewModel { RoleName = r.Name };

            return PartialView("Roles", await userRoles.ToListAsync());
        }

        public ActionResult Create()
        {
            // Show a list of available groups:
            CreateUserViewModel createUserViewModel = new CreateUserViewModel();
            IQueryable<ApplicationGroup> groups = GroupManager.Groups;

            foreach (ApplicationGroup group in groups)
            {
                SelectListItem listItem = new SelectListItem()
                {
                    Text = group.Name,
                    Value = group.Id,
                    Selected = false
                };
                createUserViewModel.GroupsList.Add(listItem);
            }
            return PartialView("Create", createUserViewModel);
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateUserViewModel createUserViewModel, string isEnabled, params string[] selectedGroups)
        {
            if (ModelState.IsValid)
            {
                if (await UserManager.UserExistAsync(null, createUserViewModel.Email))
                {
                    // Display a list of available Groups:
                    foreach (ApplicationGroup group in GroupManager.Groups)
                    {
                        SelectListItem listItem = new SelectListItem()
                        {
                            Text = group.Name,
                            Value = group.Id,
                            Selected = selectedGroups.Any(g => g == group.Id)
                        };
                        createUserViewModel.GroupsList.Add(listItem);
                    }
                    ModelState.AddModelError(string.Empty, Resources.Resources.UserExist);
                    return PartialView("Create", createUserViewModel);
                }
                ApplicationUser user = new ApplicationUser
                {
                    EmpId = createUserViewModel.EmpId,
                    FullName_En = createUserViewModel.FullName_En,
                    FullName_Ar = createUserViewModel.FullName_Ar,
                    UserName = createUserViewModel.Email,
                    Email = createUserViewModel.Email,
                    EmailConfirmed = true,
                    IsEnabled = Boolean.Parse(isEnabled)
            };
                Microsoft.AspNet.Identity.IdentityResult result = await UserManager.CreateAsync(user, createUserViewModel.Password);

                //Add User to the selected Groups
                if (result.Succeeded)
                {
                    if (selectedGroups != null)
                    {

OfflineExamSystem/Controllers/UserGroupsController.cs
using OfflineExamSystem.DDL.Repository;
using OfflineExamSystem.Helpers;
using OfflineExamSystem.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OfflineExamSystem.Controllers
{
    [LocalizedAuthorize(Roles = "Admin")]
    public class UserGroupsController : BaseController
    {
        #region Private Fields
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private ApplicationGroupManager _groupManager;
        #endregion Private Fields

        #region Public Properties
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext()
                    .GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }
        #endregion Public Properties

        #region Protected Methods
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion Protected Methods

        #region Public Methods
        public ActionResult GetGroups(string searchTerm, int pageSize, int pageNum, string userId)
        {
            var userGroups = GroupManager.GetUserGroups(userId).Select(ug => ug.Id).ToList();
            //Get the paged results and the total count of the results for this query.
            GroupRepository gr = new GroupRepository();
            List<ApplicationGroup> Groups = gr.GetGroups(searchTerm, pageSize, pageNum, userGroups);
            int count = gr.GetGroupsCount(searchTerm, pageSize, pageNum, userGroups);
            //Translate the Groups into a format the select2 dropdown expects
            Select2PagedResult pagedGroups = gr.ToSelect2Format(Groups, count);

            //Return the data as a jsonp result
            return new JsonResultHelper
            {
                Data = pagedGroups,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        // GET: UserGroups
        public async Task<ActionResult> Index(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            ViewBag.UserId = id;
            ViewBag.UserName = user.UserName;
            return View();
        }
        public PartialViewResult UserGroupsGrid(string id, string name, int? page, int? rows, string sort, string order)
        {
            var query = (from ug in db.ApplicationUserGroups.Where(ug => ug.ApplicationUserId == id)
                         join u in db.Users on ug.ApplicationUserId equals u.Id
                         join gr in db.ApplicationUserGroups on ug.ApplicationGroupId equals gr.ApplicationGroupId
                         join g in db.ApplicationGroups on gr.ApplicationGroupId equals g.Id
                         select new IndexUserGroupViewModel { UserName = u.UserName, UserId = u.Id, GroupName = g.Name, GroupId = g.Id }).DistinctBy(g => g.GroupName).AsQueryable();
            if (!string.IsNullOrEmpty(name))
                query = query.Where(q => q.GroupName.ToLower().Contains(name.ToLower()));
            if (!string.IsNullOrWhiteSpace(sort))
            {
                switch (sort.ToLower())
                {
                    case "name":
                        if (order == "asc")
                            query = query.OrderBy(q => q.GroupName);
                        else
                            query = query.OrderByDescending(q => q.GroupName);
                        break;
                    default:
                        query = query.OrderByDescending(q => q.GroupId);
                        break;
                }
            }
            else
            {
                query = query.OrderBy(q => q.GroupName);
            }
            ViewBag.TotalRows = query.Count();
            return PartialView("_UserGroupsGrid", query.Skip((page - 1 ?? 0) * (rows ?? 10)).Take(rows ?? 10).ToList());
        }

        // GET: UserGroups/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationUserGroup applicationUserGroup = await db.ApplicationUserGroups.FindAsync(id);
            if (applicationUserGroup == null)
            {
                return HttpNotFound();
            }
            return View(applicationUserGroup);
        }

        public ActionResult Add(string id)
        {
            var userGroup = new ApplicationUserGroup();
            userGroup.ApplicationUserId = id;
            return PartialView("Add", userGroup);
        }
        [HttpPost]
        public async Task<ActionResult> Add([Bind(Include = "ApplicationUserId, ApplicationGroupId")] ApplicationUserGroup userGroup, params string[] selectedGroups)
        {
            await GroupManager.SetUserGroupAsync(userGroup.ApplicationUserId, userGroup.ApplicationGroupId);
            return Json(new { Success = true });
        }

        // GET: UserGroups/Delete/5
        public async Task<ActionResult> Delete(string userId, string groupId)
        {
            if (userId == null || groupId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userGroup = await GroupManager.GetUserGroupAsync(userId, groupId);
            if (userGroup == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", userGroup);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string userId, string groupId)
        {
            if (userId == null || groupId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            await GroupManager.RemoveUserGroupAsync(userId, groupId);
            return Json(new { Success = true });
        }
        #endregion Public Methods
    }
}

OfflineExamSystem/Views/UserGroups/Add.cshtml
@model OfflineExamSystem.Models.ApplicationUserGroup

@using (Ajax.BeginForm("Add", "UserGroups", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "addContainer",
    OnSuccess = "OnSuccessAdd",
}, new { @id = "addGroup" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title">@Resources.Resources.Add</h3>
        </div>
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ApplicationUserId)
            <div class="form-horizontal">
                <h4>@Resources.Resources.Group</h4>
                <hr/>
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ApplicationGroupId, new { placeholder = Resources.Resources.ChooseGroup })
                        @Html.ValidationMessageFor(model => model.ApplicationGroupId, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
        </div>
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    <!--Roles Select2 Script -->

}
<script>
        $(document).ready(function () {
        //The url we will send our get request to
        var roleUrl = '@Url.Action("GetGroups", "UserGroups",new {userId= Model.ApplicationUserId })';
        var pageSize = 20;
            $('#ApplicationGroupId').select2(
            {
            width: 'resolve',
            tags: true,
            formatNoMatches: function (term) {
                return '@Resources.Resources.NoResult';
                    },
            formatSearching:function (term) {
                return '@Resources.Resources.Searching';
                },
            //Does the role have to enter any data before sending the ajax request
            minimumInputLength: 0,
            allowClear: true,
            ajax: {
                //How long the role has to pause their typing before sending the next request
                quietMillis: 150,
                //The url of the json service
                url: roleUrl,
                dataType: 'jsonp',
                //Our search term and what page we are on
                data: function (term, page) {
                    return {
                        pageSize: pageSize,
                        pageNum: page,
                        searchTerm: term
                    };
                },
                results: function (data, page) {
                    //Used to determine whether or not there are more results available,
                    //and if requests for more data should be sent in the infinite scrolling
                    var more = (page * pageSize) < data.Total;
                    return { results: data.Results, more: more };
                },
            }
        });

    });
    $('#ApplicationGroupId').css('width', '100%');
</script>

OfflineExamSystem/Views/UserGroups/Create.cshtml
@model OfflineExamSystem.Models.ApplicationUserGroup

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ApplicationUserGroup</h4>
        <hr/>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationUserId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationUserId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplicationGroupId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApplicationGroupId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApplicationGroupId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OfflineExamSystem/Views/UserGroups/Delete.cshtml
@model OfflineExamSystem.Models.UserGroupViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="modal-title">@Resources.Resources.Delete</h3>
</div>
<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.UserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.UserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.GroupName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GroupName)
            </dd>
        </dl>
    </div>
</div>

@using (Ajax.BeginForm("Delete", "UserGroups", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "deleteContainer",
    OnSuccess = "OnSuccessDelete",
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.UserId, new { id = "roleId" })
    @Html.HiddenFor(model => model.GroupId, new { id = "groupId" })
    <div class="modal-footer">
            <button type="submit" id="btnDelete" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> @Resources.Resources.Delete</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
    </div>
}

OfflineExamSystem/Views/UserGroups/Edit.cshtml
@model OfflineExamSystem.Models.ApplicationUserGroup

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>ApplicationUserGroup</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationUserId)
        @Html.HiddenFor(model => model.ApplicationGroupId)
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OfflineExamSystem/Views/UserGroups/Index.cshtml
@using System.Threading
@{
    ViewBag.Title = Resources.Resources.ListGroupsForUser;
}
<div class="panel panel-default m-t-20">
    <div class="panel-heading">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/@Thread.CurrentThread.CurrentCulture.Name">@Resources.Resources.Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="@Url.Action("Index","UsersAdmin")">@Resources.Resources.Users</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Resources.Resources.ListGroupsForUser [@ViewBag.UserName]</li>
            </ol>
        </nav>
        <div class="form-inline">
            <div class="form-group">
                @Html.TextBox("name", null, new { @class = "form-control", @placeholder = Resources.Resources.Name })
            </div>
            <button type="button" id="filter" class="btn btn-primary">
                <i class="fa fa-search" aria-hidden="true"></i> @Resources.Resources.Search
            </button>
            <button type="button" class="btn btn-primary add pull-right" data-id="@ViewBag.UserId" data-toggle="modal" data-target="#addModal">
                <i class="fa fa-plus" aria-hidden="true"></i> @Resources.Resources.Create
            </button>
        </div>
    </div>
    <div class="panel-body">
        @Html.AjaxGrid(Url.Action("UserGroupsGrid", new { id = ViewBag.UserId }))
    </div>
</div>
<!--Create Modal -->
<div class="modal fade" id="addModal" role="dialog" aria-labelledby="addLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id='addContainer'></div>
    </div>
</div>
<!--Delete Modal -->
<div class="modal fade" id="deleteModal" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='deleteContainer'></div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $('.mvc-grid').mvcgrid({
            reload: true
        });
        $("#filter").click(function (e) {
            $('.mvc-grid').mvcgrid({
                query: 'name=' + $('#name').val(),
                reload: true
            });
        });
    </script>
    <!--Create Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.add', function () {
                var url = '@Url.Action("Add", "UserGroups")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#addContainer').html(data);
                        $('#addModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#addModal').modal('hide');
            });
        });

        function OnSuccessAdd(data) {
            if (data.Success) {
                $('#addModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });
                $.toast({
                    heading: '@Resources.Resources.RecordCreated',
                    text: '@Resources.Resources.RecordCreatedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'success',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>
    <!--Delete Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.delete', function () {
                var url = '@Url.Action("Delete", "UserGroups")';
                var $buttonClicked = $(this);
                var userId = $buttonClicked.attr('data-user-id');
                var groupId = $buttonClicked.attr('data-group-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "userId": userId,"groupId": groupId},
                    datatype: "json",
                    success: function (data) {
                        $('#deleteContainer').html(data);
                        $('#deleteModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#deleteModal').modal('hide');
            });
        });
        function OnSuccessDelete(data) {
            if (data.Success) {
                $('#deleteModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });

                $.toast({
                    heading: '@Resources.Resources.RecordDeleted',
                    text: '@Resources.Resources.RecordDeletedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'error',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>
}