OfflineExamSystem/Controllers/RolesAdminController.cs
using OfflineExamSystem.DDL.Repository;
using OfflineExamSystem.Helpers;
using OfflineExamSystem.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OfflineExamSystem.Controllers
{
    [LocalizedAuthorize(Roles = "Admin")]
    public class RolesAdminController : BaseController
    {
        #region Private Fields
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager _userManager;
        private ApplicationRoleManager _roleManager;
        private ApplicationGroupManager _groupManager;
        #endregion Private Fields

        #region Public Constructors
        public RolesAdminController()
        {
        }

        public RolesAdminController(ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }
        #endregion Public Constructors

        #region Public Properties
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            set
            {
                _userManager = value;
            }
        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }
        #endregion Public Properties

        #region Protected Methods
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion Protected Methods

        #region Public Methods
        public ActionResult GetGroups(string searchTerm, int pageSize, int pageNum, string userId)
        {
            var userGroups = GroupManager.GetUserGroups(userId).Select(ug => ug.Id).ToList();
            //Get the paged results and the total count of the results for this query.
            GroupRepository gr = new GroupRepository();
            List<ApplicationGroup> Groups = gr.GetGroups(searchTerm, pageSize, pageNum, userGroups);
            int count = gr.GetGroupsCount(searchTerm, pageSize, pageNum, userGroups);
            //Translate the Groups into a format the select2 dropdown expects
            Select2PagedResult pagedGroups = gr.ToSelect2Format(Groups, count);

            //Return the data as a jsonp result
            return new JsonResultHelper
            {
                Data = pagedGroups,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult RoleGrid(string name, string description, string groupId, int? page, int? rows, string sort, string order)
        {
            var query = (from r in db.Roles select new IndexRoleViewModel { Id = r.Id, Name = r.Name }).AsQueryable();
            if (!string.IsNullOrEmpty(name))
                query = query.Where(q => q.Name.ToLower().Contains(name.ToLower()));
            if (!string.IsNullOrEmpty(groupId))
                query = from r in query
                        join gr in db.ApplicationGroupRoles on r.Id equals gr.ApplicationRoleId
                        where gr.ApplicationGroupId == groupId
                        select new IndexRoleViewModel { Name = r.Name };
            if (!string.IsNullOrWhiteSpace(sort))
            {
                switch (sort.ToLower())
                {
                    case "name":
                        if (order == "asc")
                            query = query.OrderBy(q => q.Name);
                        else
                            query = query.OrderByDescending(q => q.Name);
                        break;

                    default:
                        query = query.OrderByDescending(q => q.Id);
                        break;
                }
            }
            else
            {
                query = query.OrderBy(q => q.Name);
            }
            ViewBag.TotalRows = query.Count();
            return PartialView("_RoleGrid", query.Skip((page - 1 ?? 0) * (rows ?? 10)).Take(rows ?? 10).ToList());
        }
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            DetailsRoleViewModel roleViewModel = new DetailsRoleViewModel(role);
            // Get the list of Users in this Role
            var users = new List<ApplicationUser>();

            // Get the list of Users in this Role
            foreach (var user in UserManager.Users.ToList())
            {
                if (await UserManager.IsInRoleAsync(user.Id, role.Name))
                {
                    users.Add(user);
                }
            }

            ViewBag.Users = users;
            ViewBag.UserCount = users.Count();
            return PartialView(roleViewModel);
        }
        public ActionResult Create()
        {
            //Get a SelectList of Roles to choose from in the View:
            ViewBag.RolesList = new SelectList(this.RoleManager.Roles.ToList(), "Id", "Name");
            return PartialView("Create");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateRoleViewModel createRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = new ApplicationRole(createRoleViewModel.Name);
                var roleResult = await RoleManager.CreateAsync(role);
                if (!roleResult.Succeeded)
                {
                    ModelState.AddModelError(string.Empty, Resources.Resources.RoleInUse);
                    return PartialView("Create", createRoleViewModel);
                }
                return Json(new { Success = true });
            }
            return PartialView("Create", createRoleViewModel);
        }
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            EditRoleViewModel editRoleViewModel = new EditRoleViewModel { Id = role.Id, Name = role.Name };
            return PartialView("Edit", editRoleViewModel);
        }
        // POST: /Roles/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name")] EditRoleViewModel editRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = await RoleManager.FindByIdAsync(editRoleViewModel.Id);
                role.Name = editRoleViewModel.Name;
                var roleResult = await RoleManager.UpdateAsync(role);
                if (!roleResult.Succeeded)
                {
                    ModelState.AddModelError(string.Empty, Resources.Resources.RoleInUse);
                    return PartialView("Edit", editRoleViewModel);
                }
                return Json(new { Success = true });
            }
            return PartialView("Edit", editRoleViewModel);
        }
        //
        // GET: /Roles/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var role = await RoleManager.FindByIdAsync(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            DeleteRoleViewModel deleteRoleViewModel = new DeleteRoleViewModel(role);
            return PartialView("Delete", deleteRoleViewModel);
        }

        //
        // POST: /Roles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                var role = await RoleManager.FindByIdAsync(id);
                if (role == null)
                {
                    return HttpNotFound();
                }
                IdentityResult result = await RoleManager.DeleteAsync(role);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError(string.Empty, Resources.Resources.RoleInUse);
                    return PartialView("Delete", role);
                }
                return Json(new { Success = true });
            }
            return PartialView("Delete");
        }
        #endregion Public Methods
    }
}

OfflineExamSystem/Views/RolesAdmin/Create.cshtml
@model OfflineExamSystem.Models.CreateRoleViewModel
@using (Ajax.BeginForm("Create", "RolesAdmin", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "createContainer",
    OnSuccess = "OnSuccessCreate",
}, new { @id = "createGroup" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title">@Resources.Resources.Create</h3>
        </div>
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OfflineExamSystem/Views/RolesAdmin/Delete.cshtml
@model OfflineExamSystem.Models.DeleteRoleViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="modal-title">@Resources.Resources.Delete</h3>
</div>
<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
    </div>
</div>

@using (Ajax.BeginForm("Delete", "RolesAdmin", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "deleteContainer",
    OnSuccess = "OnSuccessDelete",
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <div class="modal-footer">
            <button type="submit" id="btnDelete" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> @Resources.Resources.Delete</button>
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
    </div>
}

OfflineExamSystem/Views/RolesAdmin/Details.cshtml
@model OfflineExamSystem.Models.DetailsRoleViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="modal-title">@Resources.Resources.Details</h3>
</div>
<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
        </dl>
        <h4>@Resources.Resources.ListUserPermissions</h4>
        @if (ViewBag.UserCount == 0)
        {
            <hr/>
            <p>@Resources.Resources.NoUsersInRole</p>
        }
        <table class="table">
            @foreach (var item in ViewBag.Users)
            {
                <tr>
                    <td>
                        @item.UserName
                    </td>
                </tr>
            }
        </table>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
</div>

OfflineExamSystem/Views/RolesAdmin/Edit.cshtml
@model OfflineExamSystem.Models.EditRoleViewModel
@using (Ajax.BeginForm("Edit", "RolesAdmin", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "editContainer",
    OnSuccess = "OnSuccessEdit",
}, new { @id = "editGroup" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title">@Resources.Resources.Edit</h3>
        </div>
        <div class="modal-body">
            <div class="form-horizontal">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Name)
                    </div>
                </div>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
                <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

OfflineExamSystem/Views/RolesAdmin/Index.cshtml
@using OfflineExamSystem.Helpers
@using System.Threading
@{
    ViewBag.Title = Resources.Resources.Roles;
}
<div class="panel panel-default m-t-20">
    <div class="panel-heading">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/@Thread.CurrentThread.CurrentCulture.Name">@Resources.Resources.Home</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Resources.Resources.Roles</li>
            </ol>
        </nav>
        <div class="form-inline">
            <div class="form-group">
                @Html.TextBox("name", null, new { @class = "form-control", @placeholder = Resources.Resources.Name })
            </div>
            <div class="form-group">
                @Html.TextBox("groupId", null, new { placeholder = Resources.Resources.ChooseGroup })
            </div>
            <button type="button" id="filter" class="btn btn-primary">
                <i class="fa fa-search" aria-hidden="true"></i> @Resources.Resources.Search
            </button>
            <div class="@(CultureHelper.IsRighToLeft() ? "pull-left" : "pull-right")">
                <button type="button" class="btn btn-primary create" data-id="1" data-toggle="modal" data-target="#createModal"><i class="fa fa-plus" aria-hidden="true"></i> @Resources.Resources.Create</button>
                <a href="@Url.Action("Index","UsersAdmin")" class="btn btn-danger"><i class="fa fa-users" aria-hidden="true"></i> @Resources.Resources.Users</a>
            </div>
        </div>
    </div>
    <div class="panel-body">
        @Html.AjaxGrid(Url.Action("RoleGrid"))
    </div>
</div>
<!--Create Modal -->
<div class="modal fade" id="createModal" role="dialog" aria-labelledby="createLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id='createContainer'></div>
    </div>
</div>
<!--Edit Modal -->
<div class="modal fade" id="editModal" role="dialog" aria-labelledby="editLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id='editContainer'></div>
    </div>
</div>
<!--Details Modal -->
<div class="modal fade" id="detailsModal" role="dialog" aria-labelledby="detailsLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='detailsContainer'></div>
        </div>
    </div>
</div>
<!--Delete Modal -->
<div class="modal fade" id="deleteModal" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='deleteContainer'></div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $('.mvc-grid').mvcgrid({
            reload: true
        });
        $("#filter").click(function (e) {
            $('.mvc-grid').mvcgrid({
                query: 'name=' + $('#name').val() + '&' + 'groupId=' + $('#groupId').val(),
                reload: true
            });
        });
    </script>
    <!--Create Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.create', function () {
                var url = '@Url.Action("Create", "RolesAdmin")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#createContainer').html(data);
                        $('#createModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#createModal').modal('hide');
            });
        });

        function OnSuccessCreate(data) {
            if (data.Success) {
                $('#createModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });
                $.toast({
                    heading: '@Resources.Resources.RecordCreated',
                    text: '@Resources.Resources.RecordCreatedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'success',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>
    <!--Edit Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.edit', function () {
                var url = '@Url.Action("Edit", "RolesAdmin")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#editContainer').html(data);
                        $('#editModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#editModal').modal('hide');
            });
        });
        function OnSuccessEdit(data) {
            if (data.Success) {
                $('#editModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });

                $.toast({
                    heading: '@Resources.Resources.RecordUpdated',
                    text: '@Resources.Resources.RecordUpdatedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'success',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>
    <!--Details Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.details', function () {
                var url = '@Url.Action("Details", "RolesAdmin")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#detailsContainer').html(data);
                        $('#detailsModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#detailsModal').modal('hide');
            });
        });
    </script>
    <!--Delete Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.delete', function () {
                var url = '@Url.Action("Delete", "RolesAdmin")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#deleteContainer').html(data);
                        $('#deleteModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#deleteModal').modal('hide');
            });
        });
        function OnSuccessDelete(data) {
            if (data.Success) {
                $('#deleteModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });

                $.toast({
                    heading: '@Resources.Resources.RecordDeleted',
                    text: '@Resources.Resources.RecordDeletedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'error',
                    hideAfter: 3000,
                    stack: 6
                });
                //MVCGrid.reloadGrid('Roles');
                //window.location.href = data.RedirectUrl;
            }
        }
    </script>
    <!--Roles Select2 Script -->
    <script>
    $(document).ready(function () {
        //The url we will send our get request to
        var roleUrl = '@Url.Action("GetGroups", "RolesAdmin")';
        var pageSize = 20;
        $('#groupId').select2(
            {
            width: 'resolve',
            //tags: true,
            formatNoMatches: function (term) {
                return '@Resources.Resources.NoResult';
                },
            formatSearching:function (term) {
                return '@Resources.Resources.Searching';
                },
            //Does the role have to enter any data before sending the ajax request
            minimumInputLength: 0,
            allowClear: true,
            ajax: {
                //How long the role has to pause their typing before sending the next request
                quietMillis: 150,
                //The url of the json service
                url: roleUrl,
                dataType: 'jsonp',
                //Our search term and what page we are on
                data: function (term, page) {
                    return {
                        pageSize: pageSize,
                        pageNum: page,
                        searchTerm: term
                    };
                },
                results: function (data, page) {
                    //Used to determine whether or not there are more results available,
                    //and if requests for more data should be sent in the infinite scrolling
                    var more = (page * pageSize) < data.Total;
                    return { results: data.Results, more: more };
                },
            }
        });

    });
    </script>
}