OfflineExamSystem/Controllers/GroupRolesController.cs
using OfflineExamSystem.DDL.Repository;
using OfflineExamSystem.Helpers;
using OfflineExamSystem.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace OfflineExamSystem.Controllers
{
    [LocalizedAuthorize(Roles = "Admin")]
    public class GroupRolesController : BaseController
    {
        #region Private Fields
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationGroupManager _groupManager;
        private ApplicationRoleManager _roleManager;
        #endregion Private Fields

        #region Public Properties
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion Public Properties

        #region Public Methods
        public ActionResult GetRoles(string searchTerm, int pageSize, int pageNum, string groupId)
        {
            var groupRoles = GroupManager.GetGroupRoles(groupId).Select(gr => gr.Id).ToList();
            //Get the paged results and the total count of the results for this query.
            GroupRoleRepository ur = new GroupRoleRepository();
            List<ApplicationRole> roles = ur.GetRoles(searchTerm, pageSize, pageNum, groupRoles).ToList();
            int count = ur.GetRolesCount(searchTerm, pageSize, pageNum, groupRoles);
            //Translate the roles into a format the select2 dropdown expects
            Select2PagedResult pagedRoles = ur.ToSelect2Format(roles, count);

            //Return the data as a jsonp result
            return new JsonResultHelper
            {
                Data = pagedRoles,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        // GET: GroupRoles
        public ActionResult Index(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.GroupId = id;
            ViewBag.GroupName = GroupManager.FindById(id).Name;
            return View();
        }
        public PartialViewResult GroupRolesGrid(string id, string name, string description, int? page, int? rows, string sort, string order)
        {
            var query = (from r in GroupManager.GetGroupRoles(id)
                         join gr in db.ApplicationGroupRoles on r.Id equals gr.ApplicationRoleId
                         join g in db.ApplicationGroups on gr.ApplicationGroupId equals g.Id
                         select new IndexGroupRoleViewModel { RoleId = r.Id, RoleName = r.Name, GroupId = g.Id }).DistinctBy(r => r.RoleName).AsQueryable();
            if (!string.IsNullOrEmpty(name))
                query = query.Where(q => q.RoleName.ToLower().Contains(name.ToLower()));
            if (!string.IsNullOrWhiteSpace(sort))
            {
                switch (sort.ToLower())
                {
                    case "name":
                        if (order == "asc")
                            query = query.OrderBy(q => q.RoleName);
                        else
                            query = query.OrderByDescending(q => q.RoleName);
                        break;
                    default:
                        query = query.OrderByDescending(q => q.RoleId);
                        break;
                }
            }
            else
            {
                query = query.OrderBy(q => q.RoleName);
            }
            ViewBag.TotalRows = query.Count();
            return PartialView("_GroupRolesGrid", query.Skip((page - 1 ?? 0) * (rows ?? 10)).Take(rows ?? 10).ToList());
        }

        public ActionResult Add(string id)
        {
            var groupRole = new ApplicationGroupRole();
            groupRole.ApplicationGroupId = id;
            return PartialView("Add", groupRole);
        }
        [HttpPost]
        public async Task<ActionResult> Add([Bind(Include = "ApplicationGroupId, ApplicationRoleId")] ApplicationGroupRole groupRole)
        {
            var roles = await GroupManager.AddGroupRoleAsync(groupRole.ApplicationGroupId, groupRole.ApplicationRoleId);
            return Json(new { Success = true });
        }

        public async Task<ActionResult> Delete(string groupId, string roleId)
        {
            if (groupId == null || roleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var groupRole = await GroupManager.GetGroupRoleAsync(groupId, roleId);
            if (groupRole == null)
            {
                return HttpNotFound();
            }
            return PartialView("Delete", groupRole);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string groupId, string roleId)
        {
            if (groupId == null || roleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            await GroupManager.RemoveGroupRoleAsync(groupId, roleId);
            return Json(new { Success = true });
        }
        #endregion Public Methods
    }
}

OfflineExamSystem/Controllers/GroupsAdminController.cs
using OfflineExamSystem.DDL.Repository;
using OfflineExamSystem.Helpers;
using OfflineExamSystem.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace OfflineExamSystem.Controllers
{
    [LocalizedAuthorize(Roles = "Admin")]
    public class GroupsAdminController : BaseController
    {
        #region Private Fields
        private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationGroupManager _groupManager;
        private ApplicationRoleManager _roleManager;
        #endregion Private Fields

        #region Public Properties
        public ApplicationGroupManager GroupManager
        {
            get
            {
                return _groupManager ?? new ApplicationGroupManager();
            }
            private set
            {
                _groupManager = value;
            }
        }
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }
        #endregion Public Properties

        #region Protected Methods
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion Protected Methods

        #region Public Methods
        public ActionResult GetRoles(string searchTerm, int pageSize, int pageNum)
        {
            //Get the paged results and the total count of the results for this query.
            RoleRepository ur = new RoleRepository();
            List<ApplicationRole> roles = ur.GetRoles(searchTerm, pageSize, pageNum);
            int count = ur.GetRolesCount(searchTerm, pageSize, pageNum);
            //Translate the roles into a format the select2 dropdown expects
            Select2PagedResult pagedRoles = ur.ToSelect2Format(roles, count);

            //Return the data as a jsonp result
            return new JsonResultHelper
            {
                Data = pagedRoles,
                JsonRequestBehavior = JsonRequestBehavior.AllowGet
            };
        }

        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult GroupGrid(string name, string description, string roleId, int? page, int? rows, string sort, string order)
        {
            var query = (from g in db.ApplicationGroups select new IndexGroupViewModel { Id = g.Id, Name = g.Name, Description = g.Description, ApplicationRoles = g.ApplicationRoles }).AsQueryable();
            if (!string.IsNullOrEmpty(name))
                query = query.Where(q => q.Name.ToLower().Contains(name.ToLower()));
            if (!string.IsNullOrEmpty(description))
                query = query.Where(q => q.Description.ToLower().Contains(description.ToLower()));
            if (!string.IsNullOrEmpty(roleId))
                query = query.Where(q => q.ApplicationRoles.Any(r => r.ApplicationRoleId == roleId));
            if (!string.IsNullOrWhiteSpace(sort))
            {
                switch (sort.ToLower())
                {
                    case "name":
                        if (order == "asc")
                            query = query.OrderBy(q => q.Name);
                        else
                            query = query.OrderByDescending(q => q.Name);
                        break;
                    case "description":
                        if (order == "asc")
                            query = query.OrderBy(q => q.Description);
                        else
                            query = query.OrderByDescending(q => q.Description);
                        break;

                    default:
                        query = query.OrderByDescending(q => q.Id);
                        break;
                }
            }
            else
            {
                query = query.OrderBy(q => q.Name);
            }
            ViewBag.TotalRows = query.Count();
            return PartialView("_GroupGrid", query.Skip((page - 1 ?? 0) * (rows ?? 10)).Take(rows ?? 10).ToList());
        }
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationGroup = await this.GroupManager.Groups.FirstOrDefaultAsync(g => g.Id == id);
            if (applicationGroup == null)
            {
                return HttpNotFound();
            }
            var groupRoles = this.GroupManager.GetGroupRoles(applicationGroup.Id);
            string[] RoleNames = groupRoles.Select(p => p.Name).ToArray();
            ViewBag.RolesList = RoleNames;
            ViewBag.RolesCount = RoleNames.Count();
            return PartialView("Details", applicationGroup);
        }
        public ActionResult Create()
        {
            CreateGroupViewModel createGroupViewModel = new CreateGroupViewModel();
            //Get a SelectList of Roles to choose from in the View:
            foreach (var role in RoleManager.Roles)
            {
                var listItem = new SelectListItem()
                {
                    Text = role.Name,
                    Value = role.Id,
                    Selected = false
                };
                createGroupViewModel.RolesList.Add(listItem);
            }
            return PartialView("Create", createGroupViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Name,Description")] CreateGroupViewModel createGroupViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                selectedRoles = selectedRoles ?? new string[] { };
                if (!await GroupManager.GroupExistAsync(null, createGroupViewModel.Name))
                {
                    var group = new ApplicationGroup();
                    group.Name = createGroupViewModel.Name;
                    group.Description = createGroupViewModel.Description;
                    // Create the new Group:
                    var result = await this.GroupManager.CreateGroupAsync(group);
                    if (result.Succeeded)
                    {
                        // Add the roles selected:
                        await this.GroupManager.SetGroupRolesAsync(group.Id, selectedRoles);
                    }
                    return Json(new { Success = true });
                }
                else
                {
                    ModelState.AddModelError(string.Empty, Resources.Resources.GroupExist);
                    foreach (var role in RoleManager.Roles)
                    {
                        var listItem = new SelectListItem()
                        {
                            Text = role.Name,
                            Value = role.Id,
                            Selected = selectedRoles.Any(r => r == role.Id)
                        };
                        createGroupViewModel.RolesList.Add(listItem);
                    }
                    return PartialView("Create", createGroupViewModel);
                }
            }
            // Otherwise, start over:
            foreach (var role in RoleManager.Roles)
            {
                SelectListItem listItem = new SelectListItem();
                listItem.Text = role.Name;
                listItem.Value = role.Id;
                listItem.Selected = selectedRoles == null ? false : selectedRoles.Any(r => r == role.Id);
                createGroupViewModel.RolesList.Add(listItem);
            }
            return PartialView("Create", createGroupViewModel);
        }
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ApplicationGroup applicationGroup = await this.GroupManager.FindByIdAsync(id);
            if (applicationGroup == null)
            {
                return HttpNotFound();
            }

            // Get a list, not a DbSet or queryable:
            var allRoles = await this.RoleManager.Roles.ToListAsync();
            var groupRoles = await this.GroupManager.GetGroupRolesAsync(id);

            var editGroupViewModel = new EditGroupViewModel()
            {
                Id = applicationGroup.Id,
                Name = applicationGroup.Name,
                Description = applicationGroup.Description
            };

            // load the roles/Roles for selection in the form:
            foreach (var role in allRoles)
            {
                var listItem = new SelectListItem()
                {
                    Text = role.Name,
                    Value = role.Id,
                    Selected = groupRoles.Any(g => g.Id == role.Id)
                };
                editGroupViewModel.RolesList.Add(listItem);
            }
            return PartialView("Edit", editGroupViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Description")] EditGroupViewModel editGroupViewModel, params string[] selectedRoles)
        {
            var group = await this.GroupManager.FindByIdAsync(editGroupViewModel.Id);
            if (group == null)
            {
                return HttpNotFound();
            }
            if (ModelState.IsValid)
            {
                if (!await GroupManager.GroupExistAsync(editGroupViewModel.Id, editGroupViewModel.Name))
                {

OfflineExamSystem/Views/GroupRoles/Add.cshtml
@model OfflineExamSystem.Models.ApplicationGroupRole

@using (Ajax.BeginForm("Add", "GroupRoles", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "addContainer",
    OnSuccess = "OnSuccessAdd"
}, new { @id = "addGroup" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
                <span aria-hidden="true">&times;</span>
            </button>
            <h3 class="modal-title">@Resources.Resources.Create</h3>
        </div>
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.HiddenFor(model => model.ApplicationGroupId)
            <div class="form-horizontal">
                <h4>ApplicationGroup</h4>
                <hr />
                <div class="form-group">
                    <div class="col-md-10">
                        @Html.TextBoxFor(model => model.ApplicationRoleId, new { id = "ApplicationRoleId", placeholder = Resources.Resources.ChooseRole })
                        @Html.ValidationMessageFor(model => model.ApplicationRoleId, "", new { @class = "text-danger" })
                    </div>
                </div>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="modal-footer">
            <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> @Resources.Resources.Save</button>
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times" aria-hidden="true"></i> @Resources.Resources.Close</button>
        </div>
    </div>
}

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
}
<!--Roles Select2 Script -->
<script>
    $(document).ready(function () {
        //The url we will send our get request to
        var roleUrl = '@Url.Action("GetRoles", "GroupRoles",new {groupId= Model.ApplicationGroupId })';
        var pageSize = 20;
            $('#ApplicationRoleId').select2(
            {
            width: 'resolve',
            tags: true,
            formatNoMatches: function (term) {
                return '@Resources.Resources.NoResult';
                    },
            formatSearching:function (term) {
                return '@Resources.Resources.Searching';
                },
            //Does the role have to enter any data before sending the ajax request
            minimumInputLength: 0,
            allowClear: true,
            ajax: {
                //How long the role has to pause their typing before sending the next request
                quietMillis: 150,
                //The url of the json service
                url: roleUrl,
                dataType: 'jsonp',
                //Our search term and what page we are on
                data: function (term, page) {
                    return {
                        pageSize: pageSize,
                        pageNum: page,
                        searchTerm: term
                    };
                },
                results: function (data, page) {
                    //Used to determine whether or not there are more results available,
                    //and if requests for more data should be sent in the infinite scrolling
                    var more = (page * pageSize) < data.Total;
                    return { results: data.Results, more: more };
                },
            }
        });

    });
    $('#ApplicationRoleId').css('width', '100%');
</script>

OfflineExamSystem/Views/GroupRoles/Delete.cshtml
@model OfflineExamSystem.Models.GroupRoleViewModel
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">
        <span aria-hidden="true">&times;</span>
    </button>
    <h3 class="modal-title">@Resources.Resources.Delete</h3>
</div>
<div class="modal-body">
    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.GroupName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.GroupName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.RoleName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.RoleName)
            </dd>
        </dl>
    </div>
</div>

@using (Ajax.BeginForm("Delete", "GroupRoles", null, new AjaxOptions()
{
    HttpMethod = "POST",
    UpdateTargetId = "deleteContainer",
    OnSuccess = "OnSuccessDelete",
}))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.GroupId, new { id = "groupId" })
    @Html.HiddenFor(model => model.RoleId, new { id = "roleId" })
    <div class="modal-footer">
        <button type="submit" id="btnDelete" class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"></i> @Resources.Resources.Delete</button>  
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-window-close" aria-hidden="true"></i> @Resources.Resources.Close</button>
    </div>
}

OfflineExamSystem/Views/GroupRoles/Index.cshtml
@using System.Threading
@{
    ViewBag.Title = Resources.Resources.ListGroupPermissions;
}
<div class="panel panel-default m-t-20">
    <div class="panel-heading">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/@Thread.CurrentThread.CurrentCulture.Name">@Resources.Resources.Home</a></li>
                <li class="breadcrumb-item active" aria-current="page"><a href="@Url.Action("Index","GroupsAdmin")">@Resources.Resources.Groups</a></li>
                <li class="breadcrumb-item active" aria-current="page">@Resources.Resources.ListGroupPermissions [@ViewBag.GroupName]</li>
            </ol>
        </nav>
        <div class="form-inline">
            <div class="form-group">
                @Html.TextBox("name", null, new { @class = "form-control", @placeholder = Resources.Resources.Name })
            </div>
            <button type="button" id="filter" class="btn btn-primary">
                <i class="fa fa-search" aria-hidden="true"></i> @Resources.Resources.Search
            </button>
            <button type="button" class="btn btn-primary add pull-right" data-id="@ViewBag.GroupId" data-toggle="modal" data-target="#addModal">
                <i class="fa fa-plus" aria-hidden="true"></i> @Resources.Resources.Create
            </button>
        </div>
    </div>
    <div class="panel-body">
        @Html.AjaxGrid(Url.Action("GroupRolesGrid", new { id = ViewBag.GroupId }))
    </div>
</div>
<!--Create Modal -->
<div class="modal fade" id="addModal" role="dialog" aria-labelledby="addLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div id='addContainer'></div>
    </div>
</div>
<!--Delete Modal -->
<div class="modal fade" id="deleteModal" role="dialog" aria-labelledby="deleteLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='deleteContainer'></div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        $('.mvc-grid').mvcgrid({
            reload: true
        });
        $("#filter").click(function (e) {
            $('.mvc-grid').mvcgrid({
                query: 'name=' + $('#name').val(),
                reload: true
            });
        });
    </script>
    <!--Create Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.add', function () {
                var url = '@Url.Action("Add", "GroupRoles")';
                var $buttonClicked = $(this);
                var id = $buttonClicked.attr('data-id');
                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "Id": id },
                    datatype: "json",
                    success: function (data) {
                        $('#addContainer').html(data);
                        $('#addModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#addModal').modal('hide');
            });
        });

        function OnSuccessAdd(data) {
            if (data.Success) {
                $('#addModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });
                $.toast({
                    heading: '@Resources.Resources.RecordCreated',
                    text: '@Resources.Resources.RecordCreatedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'success',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>
    <!--Delete Modal Script -->
    <script>
        $(function () {
            $(document).on('click', '.delete', function () {
                var url = '@Url.Action("Delete", "GroupRoles")';
                var $buttonClicked = $(this);
                var groupId = $buttonClicked.attr('data-group-id');
                var roleId = $buttonClicked.attr('data-role-id');

                $.ajax({
                    type: "GET",
                    url: url,
                    contentType: "application/json; charset=utf-8",
                    data: { "groupId": groupId, "roleId": roleId},
                    datatype: "json",
                    success: function (data) {
                        $('#deleteContainer').html(data);
                        $('#deleteModal').modal('show');
                    },
                    error: function () {
                        alert("Dynamic content load failed.");
                    }
                });
            });
            $("#closbtn").click(function () {
                $('#deleteModal').modal('hide');
            });
        });
        function OnSuccessDelete(data) {
            if (data.Success) {
                $('#deleteModal').modal('hide');
                $('.mvc-grid').mvcgrid({ reload: true });
                $.toast({
                    heading: '@Resources.Resources.RecordDeleted',
                    text: '@Resources.Resources.RecordDeletedSuccessfully',
                    position: 'top-right',
                    loaderBg: '#ff6849',
                    icon: 'error',
                    hideAfter: 3000,
                    stack: 6
                });
            }
        }
    </script>

}